# Generated by Django 5.0.6 on 2024-06-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('empemail', models.CharField(max_length=200)),
                ('empsal', models.FloatField()),
                ('empadd', models.CharField(max_length=500)),
            ],
        ),
    ]
