# Generated by Django 5.0.4 on 2024-07-04 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='emenities',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='show_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.show'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Emenitites',
        ),
    ]
