# Generated by Django 5.0.6 on 2024-07-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('esalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=100)),
                ('edepartment', models.CharField(max_length=200)),
            ],
        ),
    ]
